name: CI

on:
  push:
    branches: ["main"]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:

      # Initialization
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependency
        run: npm install
      # Create Firefox artifacts
      - name: Create Firefox artifacts
        run: npm run release
      - uses: actions/upload-artifact@v3
        with:
          name: LExtension
          path: web-ext-artifacts/lextension*.zip